version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"

  - package-ecosystem: gradle
    directory: /app/android
    schedule:
      interval: monthly
    commit-message:
      prefix: "build"
