// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tasks,
    attachments,
    settings,
    idxTasksCurrent,
    idxTasksParent,
    idxAttachmentsTask,
  ];
  late final Shape0 tasks = Shape0(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 attachments = Shape1(
    source: i0.VersionedTable(
      entityName: 'attachments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_5,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_30, _column_31, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxTasksCurrent = i1.Index(
    'idx_tasks_current',
    'CREATE INDEX idx_tasks_current ON tasks (status, deleted_at, rank)',
  );
  final i1.Index idxTasksParent = i1.Index(
    'idx_tasks_parent',
    'CREATE INDEX idx_tasks_parent ON tasks (parent_id)',
  );
  final i1.Index idxAttachmentsTask = i1.Index(
    'idx_attachments_task',
    'CREATE INDEX idx_attachments_task ON attachments (task_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rank =>
      columnsByName['rank']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorKey =>
      columnsByName['color_key']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dueDate =>
      columnsByName['due_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get parentId =>
      columnsByName['parent_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rank',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'due_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES tasks(id)',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'local\'',
      defaultValue: const i1.CustomExpression('\'local\''),
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'external_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get origin =>
      columnsByName['origin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mime =>
      columnsByName['mime']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get relPath =>
      columnsByName['rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayRelPath =>
      columnsByName['display_rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbRelPath =>
      columnsByName['thumb_rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originalName =>
      columnsByName['original_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceUrl =>
      columnsByName['source_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceHost =>
      columnsByName['source_host']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get snapshotRelPath =>
      columnsByName['snapshot_rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get snapshotAt =>
      columnsByName['snapshot_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pageCount =>
      columnsByName['page_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES tasks(id)',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rel_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_rel_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumb_rel_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_host',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'snapshot_rel_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'snapshot_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'page_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sha256',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tasks,
    attachments,
    settings,
    idxTasksCurrent,
    idxTasksParent,
    idxAttachmentsTask,
    idxAttachmentsTaskPosition,
  ];
  late final Shape0 tasks = Shape0(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 attachments = Shape3(
    source: i0.VersionedTable(
      entityName: 'attachments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_5,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_30, _column_31, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxTasksCurrent = i1.Index(
    'idx_tasks_current',
    'CREATE INDEX idx_tasks_current ON tasks (status, deleted_at, rank)',
  );
  final i1.Index idxTasksParent = i1.Index(
    'idx_tasks_parent',
    'CREATE INDEX idx_tasks_parent ON tasks (parent_id)',
  );
  final i1.Index idxAttachmentsTask = i1.Index(
    'idx_attachments_task',
    'CREATE INDEX idx_attachments_task ON attachments (task_id)',
  );
  final i1.Index idxAttachmentsTaskPosition = i1.Index(
    'idx_attachments_task_position',
    'CREATE INDEX idx_attachments_task_position ON attachments (task_id, position, id)',
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get origin =>
      columnsByName['origin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mime =>
      columnsByName['mime']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get relPath =>
      columnsByName['rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayRelPath =>
      columnsByName['display_rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbRelPath =>
      columnsByName['thumb_rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originalName =>
      columnsByName['original_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceUrl =>
      columnsByName['source_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceHost =>
      columnsByName['source_host']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get snapshotRelPath =>
      columnsByName['snapshot_rel_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get snapshotAt =>
      columnsByName['snapshot_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pageCount =>
      columnsByName['page_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
